// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4-t8uImARGgKai_bGYegGZjpT8MZWtgw',
    appId: '1:406187198142:web:351b5b94c6656c477240ef',
    messagingSenderId: '406187198142',
    projectId: 'chatapp-f5446',
    authDomain: 'chatapp-f5446.firebaseapp.com',
    storageBucket: 'chatapp-f5446.appspot.com',
    measurementId: 'G-1RV2YG4CHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodvb_Z_xH2Mr3lx8mDHgXnNM5UhFj4kI',
    appId: '1:406187198142:android:19548fe6192745927240ef',
    messagingSenderId: '406187198142',
    projectId: 'chatapp-f5446',
    storageBucket: 'chatapp-f5446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzwY8SG-AnGl0abbRHfOES_ZeAq2Wr30',
    appId: '1:406187198142:ios:d0c648d346a1dd5d7240ef',
    messagingSenderId: '406187198142',
    projectId: 'chatapp-f5446',
    storageBucket: 'chatapp-f5446.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzwY8SG-AnGl0abbRHfOES_ZeAq2Wr30',
    appId: '1:406187198142:ios:503101aa6edf657e7240ef',
    messagingSenderId: '406187198142',
    projectId: 'chatapp-f5446',
    storageBucket: 'chatapp-f5446.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
